CREATE TABLE IF NOT EXISTS ratings (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(10)
);

CREATE TABLE IF NOT EXISTS genres (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50)
);

CREATE TABLE IF NOT EXISTS films (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  description varchar(2000),
  rating_id int4,
  release_date date,
  duration int4,
  FOREIGN KEY (rating_id) REFERENCES ratings (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS genres_on_films (
  genre_id int4 NOT NULL,
  film_id int8 NOT NULL,
  PRIMARY KEY (genre_id, film_id),
  FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE SET NULL,
  FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(50) NOT NULL,
  login varchar(200) NOT NULL,
  password varchar(50),
  name varchar(100),
  birthday date
);

CREATE TABLE IF NOT EXISTS likes_on_films (
  film_id int8 NOT NULL,
  user_id int8 NOT NULL,
  PRIMARY KEY (film_id, user_id),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends (
  user_id int8 NOT NULL,
  friend_id int8 NOT NULL,
  PRIMARY KEY (user_id, friend_id),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id int8 NOT NULL,
  user_id int8 NOT NULL,
  isPositive boolean NOT NULL,
  content varchar(500) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ratings_on_reviews (
  user_id int8 NOT NULL,
  review_id int8 NOT NULL,
  isLike boolean NOT NULL,
  PRIMARY KEY (user_id, review_id),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS directors (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS directors_on_films (
  director_id int8 NOT NULL,
  film_id int8 NOT NULL,
  PRIMARY KEY (director_id, film_id),
  FOREIGN KEY (director_id) REFERENCES directors (id) ON DELETE CASCADE,
  FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS operations (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS audit (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  create_time timestamp NOT NULL,
  user_id int8 NOT NULL,
  event_id int4 NOT NULL,
  operation_id int4 NOT NULL,
  entity_id int8 NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
  FOREIGN KEY (operation_id) REFERENCES operations (id) ON DELETE RESTRICT
);